# Generated by Django 5.0.1 on 2024-03-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerUser',
            new_name='CustomUser',
        ),
    ]
