# Generated by Django 5.0.1 on 2024-10-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0018_rename_first_call_satus_student_first_call_status_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='centers',
            field=models.ManyToManyField(blank=True, to='centers.center'),
        ),
    ]
