# Generated by Django 5.0.1 on 2024-03-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_options_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_edit_first_call', 'Can edit first call'), ('can_edit_second_call', 'Can edit second call'), ('can_add_students', 'Can add students'), ('can_access_admin', 'Can access Django admin'), ('can_add_centers', 'Can add centers'), ('can_add_grouptrial', 'Can add groups trial'), ('can_add_grouppermanent', 'Can add groups permanent')]},
        ),
    ]
