version: "3.8"

services:
  app:
    build: .
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres:16.1-alpine
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
        - POSTGRES_HOST
        - POSTGRES_PORT
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure
