networks:
  dev:

services:
  app:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 crmschool.wsgi:application
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - postgres
    restart: on-failure
    networks:
        - dev

  postgres:
    image: postgres:16.1-alpine
    ports:
        - "5433:5432"
    environment:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
        - POSTGRES_HOST
        - POSTGRES_PORT
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure
    networks:
        - dev

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure
    networks:
        - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:81"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - static_volume:/app/staticfiles
    depends_on:
      - app
    restart: on-failure
    networks:
        - dev

volumes:
  static_volume:
  postgres_data: