# Generated by Django 5.0.1 on 2024-02-16 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('school', models.TextField(blank=True, max_length=30, null=True)),
                ('class_number', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=1)),
                ('student_add_date', models.DateTimeField(auto_now_add=True)),
                ('first_call', models.CharField(blank=True, max_length=50, null=True)),
                ('first_call_satus', models.CharField(blank=True, max_length=50, null=True)),
                ('trial_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('trial_status', models.BooleanField(blank=True, default=False, null=True)),
                ('comment_first_call', models.TextField(blank=True, max_length=250, null=True)),
                ('second_call', models.CharField(blank=True, max_length=50, null=True)),
                ('second_call_satus', models.CharField(blank=True, max_length=50, null=True)),
                ('add_to_group', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_second_call', models.TextField(blank=True, max_length=250, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.center')),
            ],
        ),
    ]
