# Generated by Django 5.0.1 on 2024-02-16 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.center')),
            ],
        ),
    ]
