# Generated by Django 5.0.1 on 2024-02-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='add_to_group',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_call',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_call_satus',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone_number',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_call',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_call_satus',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_full_name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone_number',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='trial_registration',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
