# Generated by Django 5.0.1 on 2024-03-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_alter_student_first_call_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_call_satus',
            field=models.CharField(blank=True, choices=[(' ', ' '), ('Так, прийдуть на пробне', 'Так, прийдуть на пробне'), ('Ні', 'Ні'), ('Думають', 'Думають'), ('Невірний номер', 'Невірний номер'), ('На наступний тиждень', 'На наступний тиждень'), ('Передзвонити пізніше', 'Передзвонити пізніше'), ('Примітка', 'Примітка'), ('Не беруть телефон', 'Не беруть телефон')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='trial_status',
            field=models.CharField(blank=True, choices=[(' ', ' '), ('Так, був на пробному', 'Так, був на пробному'), ('Ні, не був', 'Ні, не був')], max_length=80, null=True),
        ),
    ]
