# Generated by Django 5.0.1 on 2024-03-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0009_alter_student_first_call_satus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='GroupPermanent',
        ),
    ]
