# Generated by Django 5.0.1 on 2024-04-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0010_rename_group_grouppermanent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_call',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
