# Generated by Django 5.0.1 on 2024-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0011_alter_student_first_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='unique_link',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
