# Generated by Django 5.0.1 on 2024-04-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0011_alter_student_first_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='unique_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
