# Generated by Django 5.0.1 on 2024-04-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0012_center_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='unique_id',
        ),
    ]
