# Generated by Django 5.0.1 on 2024-05-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0013_alter_center_unique_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='unique_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
