# Generated by Django 5.0.1 on 2024-04-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0014_alter_student_first_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_call',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
