# Generated by Django 5.0.1 on 2024-10-02 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0015_student_parent_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='add_to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.grouppermanent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='trial_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.grouptrial'),
        ),
    ]
