# Generated by Django 5.0.1 on 2024-10-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0016_alter_student_add_to_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
