# Generated by Django 5.0.1 on 2024-10-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0017_student_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_call_satus',
            new_name='first_call_status',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='second_call_satus',
            new_name='second_call_status',
        ),
    ]
