# Generated by Django 5.0.1 on 2024-10-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0018_rename_first_call_satus_student_first_call_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='custom_id',
            field=models.IntegerField(default=0),
        ),
    ]
